version: "3.8"
services:
  bank-dashboard-app:
    container_name: bank-dashboard-app
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:alpine"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - bank-dashboard-app
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

