# home/models.py

from apps import db

class Customer(db.Model):
    __tablename__ = 'customers'
    customer_id = db.Column(db.Integer, primary_key=True)
    full_name = db.Column(db.String(255), nullable=False)
    place_of_birth = db.Column(db.String(255), nullable=False)
    date_of_birth = db.Column(db.DateTime, nullable=False)
    citizenship = db.Column(db.String(100), nullable=False)
    gender = db.Column(db.String(10), nullable=False)
    number_of_children = db.Column(db.Integer, nullable=False)
    marital_status = db.Column(db.String(50), nullable=False)
    occupation = db.Column(db.String(255), nullable=False)
    customer_registration_date = db.Column(db.DateTime, nullable=False)
    monthly_income = db.Column(db.Numeric(15, 2), nullable=False)
    education_level = db.Column(db.String(100), nullable=False)
    city = db.Column(db.String(100), nullable=False)
    number_of_loans = db.Column(db.Integer, nullable=False)

    # Relationships
    credit_scores = db.relationship('CreditScore', backref='customer', lazy=True)
    customer_loans = db.relationship('CustomerLoan', backref='customer', lazy=True)
    surveys = db.relationship('Survey', backref='customer', lazy=True)


class CreditScore(db.Model):
    __tablename__ = 'credit_scores'
    customer_id = db.Column(db.Integer, db.ForeignKey('customers.customer_id'), nullable=False, primary_key=True)
    credit_score = db.Column(db.Integer, nullable=False)


class CustomerLoan(db.Model):
    __tablename__ = 'customer_loans'
    document_id = db.Column(db.String(50), primary_key=True)
    customer_id = db.Column(db.Integer, db.ForeignKey('customers.customer_id'), nullable=False)
    product_type = db.Column(db.String(100), nullable=False)
    loan_type = db.Column(db.String(100), nullable=False)
    currency_type = db.Column(db.String(10), nullable=False)
    loan_start_date = db.Column(db.DateTime, nullable=False)
    loan_end_date = db.Column(db.DateTime, nullable=False)
    loan_status = db.Column(db.String(50), nullable=False)
    requested_amount = db.Column(db.Numeric(15, 2), nullable=False)
    approved_amount = db.Column(db.Numeric(15, 2), nullable=False)
    principal_debt = db.Column(db.Numeric(15, 2), nullable=False)
    total_debt = db.Column(db.Numeric(15, 2), nullable=False)
    secondary_purpose_code = db.Column(db.String(50), nullable=True)
    secondary_purpose_description = db.Column(db.String(255), nullable=True)
    tertiary_purpose_code = db.Column(db.String(50), nullable=True)
    tertiary_purpose_description = db.Column(db.String(255), nullable=True)
    product_type_biznes_kredileri = db.Column(db.String(10), nullable=True)
    product_type_partnyorluq_kredileri = db.Column(db.String(10), nullable=True)
    product_type_istehlak = db.Column(db.String(10), nullable=True)
    product_type_eh_layihələri = db.Column(db.String(10), nullable=True)

class Survey(db.Model):
    __tablename__ = 'surveys'
    customer_id = db.Column(db.Integer, db.ForeignKey('customers.customer_id'), nullable=False, primary_key=True)
    country_of_residence = db.Column(db.String(100), nullable=False)
    citizenship = db.Column(db.String(100), nullable=False)
    is_politician = db.Column(db.String(10), nullable=False)
    has_political_affiliation = db.Column(db.String(10), nullable=False)
    account_purpose = db.Column(db.String(255), nullable=False)
    annual_account_activity_range = db.Column(db.String(50), nullable=False)
    current_account_local_currency_balance = db.Column(db.String(50), nullable=False)
    number_of_current_accounts = db.Column(db.String(50), nullable=False)
    savings_account_local_currency_balance = db.Column(db.String(50), nullable=False)
    number_of_savings_accounts = db.Column(db.String(50), nullable=False)
    investment_account_local_currency_balance = db.Column(db.String(50), nullable=False)
    number_of_investment_accounts = db.Column(db.String(50), nullable=False)
    authorized_signatory_country_of_residence = db.Column(db.String(100), nullable=True)
    authorized_signatory_citizenship = db.Column(db.String(100), nullable=True)
    company_partner_citizenship = db.Column(db.String(100), nullable=True)
    number_of_family_members = db.Column(db.Integer, nullable=False)
    gender = db.Column(db.String(10), nullable=False)
    marital_status = db.Column(db.String(50), nullable=False)
    education_level = db.Column(db.String(100), nullable=False)
    occupation = db.Column(db.String(255), nullable=False)
    age = db.Column(db.Integer, nullable=False)
    additional_income = db.Column(db.Float, nullable=True)
    has_collateral = db.Column(db.String(10), nullable=False)
    owns_valuable_items = db.Column(db.String(10), nullable=False)
    owns_real_estate = db.Column(db.String(10), nullable=False)
    loan_purpose = db.Column(db.String(255), nullable=False)
    loan_branch = db.Column(db.String(100), nullable=False)
    number_of_loans = db.Column(db.Integer, nullable=False)
    loan_month = db.Column(db.String(50), nullable=False)
    primary_income_percentage = db.Column(db.String(20), nullable=False)
    income_type = db.Column(db.String(100), nullable=False)
    expense_to_income_ratio = db.Column(db.Float, nullable=False)
    negative_comment_from_loan_department = db.Column(db.String(10), nullable=False)
    years_of_employment = db.Column(db.String(50), nullable=False)
    years_in_same_residence = db.Column(db.Integer, nullable=False)
    job_position = db.Column(db.String(255), nullable=False)
    movable_property_value_in_usd = db.Column(db.Numeric(15, 2), nullable=False)
    immovable_property_value_land_in_usd = db.Column(db.Numeric(15, 2), nullable=False)
    second_property_value_in_usd = db.Column(db.Numeric(15, 2), nullable=False)
    immovable_property_value_house_in_usd = db.Column(db.Numeric(15, 2), nullable=False)
    is_customer_on_banned_list = db.Column(db.String(10), nullable=False)
    is_regular_customer = db.Column(db.String(10), nullable=False)
    total_score = db.Column(db.Integer, nullable=False)

from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class ModelData(db.Model):
    __tablename__ = 'model_data'
    
    Customer_ID = db.Column(db.Integer, primary_key=True, autoincrement=True)
    Number_of_Children = db.Column(db.Integer)
    Monthly_Income = db.Column(db.Numeric(15, 2))
    Number_of_Loans = db.Column(db.Integer)
    Full_Name_Ferdi_Fiziki_Shexs_Rezident = db.Column(db.String(255))
    Full_Name_Ferdi_Sahibkar_Rezident = db.Column(db.String(255))
    Place_of_Birth_QIRGIZISTAN = db.Column(db.String(100))
    Place_of_Birth_RUSIYA_FEDERASIYASI = db.Column(db.String(100))
    Place_of_Birth_TACIKISTAN = db.Column(db.String(100))
    Place_of_Birth_TATARISTAN = db.Column(db.String(100))
    Place_of_Birth_TURKMENISTAN = db.Column(db.String(100))
    Place_of_Birth_OZBEKISTAN = db.Column(db.String(100))
    Place_of_Birth_AFGANISTAN = db.Column(db.String(100))
    Age = db.Column(db.Integer)
    Citizenship_TACIKISTAN = db.Column(db.String(100))
    Gender_QADIN = db.Column(db.String(10))
    Marital_Status_DUL = db.Column(db.String(10))
    Marital_Status_EVLI = db.Column(db.String(10))
    Marital_Status_SUBAY = db.Column(db.String(10))
    Occupation_HAYVANCILIK = db.Column(db.String(50))
    Occupation_HIZMETLER = db.Column(db.String(50))
    Occupation_MORTGAGES = db.Column(db.String(50))
    Occupation_TARIM = db.Column(db.String(50))
    Occupation_TICARET = db.Column(db.String(50))
    Occupation_URETIM = db.Column(db.String(50))
    Log_Monthly_Income = db.Column(db.Numeric(15, 6))
    Education_Level_Higher_Education = db.Column(db.String(50))
    Education_Level_Incomplete_Secondary_Education = db.Column(db.String(50))
    Education_Level_Other_Education = db.Column(db.String(50))
    Education_Level_Secondary_Education = db.Column(db.String(50))
    Education_Level_Secondary_Education_with_Specialisation = db.Column(db.String(50))
    Total_Loan_Amount = db.Column(db.Numeric(15, 2))
    Average_Loan_Amount = db.Column(db.Numeric(15, 2))
    Loan_Amount_Range = db.Column(db.String(50))
    Active_Loans_Count = db.Column(db.Integer)
    Overdue_Loans_Count = db.Column(db.Integer)
    Severely_Overdue_Loans_Count = db.Column(db.Integer)
    legal_loans_count = db.Column(db.Integer)
    woff_loans_count = db.Column(db.Integer)
    Loan_Status_Changes = db.Column(db.String(255))
    Average_Credit_Duration = db.Column(db.Integer)
    Total_Credit_Duration = db.Column(db.Integer)
    Product_Type_BIZNES_KREDITLERI = db.Column(db.String(100))
    Product_Type_PARTNYORLUQ_KREDITLERI = db.Column(db.String(100))
    Product_Type_ISTEHLAK = db.Column(db.String(100))
    Product_Type_AH_LAYIHELARI = db.Column(db.String(100))
    Total_Debt = db.Column(db.Numeric(15, 2))
    Debt_Income_Ratio = db.Column(db.Numeric(5, 2))
    Number_of_Family_Members = db.Column(db.Integer)
    Is_Politician_Hayir = db.Column(db.String(10))
    Has_Political_Affiliation_Hayir = db.Column(db.String(10))
    Account_Purpose_SBER_HESAP = db.Column(db.String(50))
    Account_Purpose_TASARRUF_HESABI = db.Column(db.String(50))
    Account_Purpose_ULUSLARARASI_PARA_TRANSFERI = db.Column(db.String(50))
    Account_Purpose_YURTICI_HAVALE = db.Column(db.String(50))
    Has_Collateral_Hayir = db.Column(db.String(10))
    Owns_Valuable_Items_Hayir = db.Column(db.String(10))
    Owns_Real_Estate_Hayir = db.Column(db.String(10))
    Loan_Purpose_ISLETME_SERMAYESI = db.Column(db.String(50))
    Loan_Purpose_MULK_ALIMI = db.Column(db.String(50))
    Loan_Purpose_SABIT_VARLIKLAR = db.Column(db.String(50))
    Loan_Purpose_TADILAT = db.Column(db.String(50))
    Loan_Purpose_TARIM = db.Column(db.String(50))
    Income_Type_DIGER = db.Column(db.String(50))
    Income_Type_EK_IS = db.Column(db.String(50))
    Income_Type_HAVALE = db.Column(db.String(50))
    Income_Type_KIRA_GELIRI = db.Column(db.String(50))
    Negative_Comment_from_Loan_Department_Hayir = db.Column(db.String(10))
    Job_Position_Diger = db.Column(db.String(50))
    Job_Position_Ozel_Sektor = db.Column(db.String(50))
    Job_Position_Ozel_Sektor_Teknik = db.Column(db.String(50))
    Job_Position_Sirket_Sahibi = db.Column(db.String(50))
    Job_Position_Yonetici = db.Column(db.String(50))
    Is_Customer_on_Banned_List_Hayir = db.Column(db.String(10))
    Is_Regular_Customer_Evet = db.Column(db.String(10))
    Annual_Account_Activity_Range_100000_500000 = db.Column(db.String(50))
    Annual_Account_Activity_Range_30000_100000 = db.Column(db.String(50))
    Annual_Account_Activity_Range_500000_99999999999 = db.Column(db.String(50))
    Annual_Account_Activity_Range_Diger = db.Column(db.String(50))
    Target_Worst = db.Column(db.String(255))
