CREATE TABLE customers (
    customer_id INT,
    full_name VARCHAR(255),
    place_of_birth VARCHAR(255),
    date_of_birth DATETIME,
    citizenship VARCHAR(100),
    gender VARCHAR(10),
    number_of_children INT,
    marital_status VARCHAR(50),
    occupation VARCHAR(255),
    customer_registration_date DATETIME,
    monthly_income DECIMAL(15,2),
    education_level VARCHAR(100),
    city VARCHAR(100),
    number_of_loans INT,
    PRIMARY KEY (customer_id)
);

CREATE TABLE credit_scores (
    customer_id INT,
    credit_score INT,
    PRIMARY KEY (customer_id),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE customer_loans (
    document_id VARCHAR(50) PRIMARY KEY,
    customer_id INT,
    product_type VARCHAR(100),
    loan_type VARCHAR(100),
    currency_type VARCHAR(10),
    loan_start_date DATETIME,
    loan_end_date DATETIME,
    loan_status VARCHAR(50),
    requested_amount DECIMAL(15,2),
    approved_amount DECIMAL(15,2),
    principal_debt DECIMAL(15,2),
    total_debt DECIMAL(15,2),
    secondary_purpose_code VARCHAR(50),
    secondary_purpose_description VARCHAR(255),
    tertiary_purpose_code VARCHAR(50),
    tertiary_purpose_description VARCHAR(255),
    product_type_biznes_kredileri VARCHAR(10),
    product_type_partnyorluq_kredileri VARCHAR(10),
    product_type_istehlak VARCHAR(10),
    product_type_eh_layihələri VARCHAR(10),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE surveys (
    customer_id INT,
    country_of_residence VARCHAR(100),
    citizenship VARCHAR(100),
    is_politician VARCHAR(10),
    has_political_affiliation VARCHAR(10),
    account_purpose VARCHAR(255),
    annual_account_activity_range VARCHAR(50),
    current_account_local_currency_balance VARCHAR(50),
    number_of_current_accounts VARCHAR(50),
    savings_account_local_currency_balance VARCHAR(50),
    number_of_savings_accounts VARCHAR(50),
    investment_account_local_currency_balance VARCHAR(50),
    number_of_investment_accounts VARCHAR(50),
    authorized_signatory_country_of_residence VARCHAR(100),
    authorized_signatory_citizenship VARCHAR(100),
    company_partner_citizenship VARCHAR(100),
    number_of_family_members INT,
    gender VARCHAR(10),
    marital_status VARCHAR(50),
    education_level VARCHAR(100),
    occupation VARCHAR(255),
    age INT,
    additional_income FLOAT,
    has_collateral VARCHAR(10),
    owns_valuable_items VARCHAR(10),
    owns_real_estate VARCHAR(10),
    loan_purpose VARCHAR(255),
    loan_branch VARCHAR(100),
    number_of_loans INT,
    loan_month VARCHAR(50),
    primary_income_percentage VARCHAR(20),
    income_type VARCHAR(100),
    expense_to_income_ratio FLOAT,
    negative_comment_from_loan_department VARCHAR(10),
    years_of_employment VARCHAR(50),
    years_in_same_residence INT,
    job_position VARCHAR(255),
    movable_property_value_in_usd DECIMAL(15,2),
    immovable_property_value_land_in_usd DECIMAL(15,2),
    second_property_value_in_usd DECIMAL(15,2),
    immovable_property_value_house_in_usd DECIMAL(15,2),
    is_customer_on_banned_list VARCHAR(10),
    is_regular_customer VARCHAR(10),
    total_score INT,
    PRIMARY KEY (customer_id),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);


CREATE TABLE model_data (
    Customer_ID INT PRIMARY KEY AUTO_INCREMENT,
    Number_of_Children INT,
    Monthly_Income DECIMAL(15, 2),
    Number_of_Loans INT,
    Full_Name_Ferdi_Fiziki_Shexs_Rezident VARCHAR(255),
    Full_Name_Ferdi_Sahibkar_Rezident VARCHAR(255),
    Place_of_Birth_QIRGIZISTAN VARCHAR(100),
    Place_of_Birth_RUSIYA_FEDERASIYASI VARCHAR(100),
    Place_of_Birth_TACIKISTAN VARCHAR(100),
    Place_of_Birth_TATARISTAN VARCHAR(100),
    Place_of_Birth_TURKMENISTAN VARCHAR(100),
    Place_of_Birth_OZBEKISTAN VARCHAR(100),
    Place_of_Birth_AFGANISTAN VARCHAR(100),
    Age INT,
    Citizenship_TACIKISTAN VARCHAR(100),
    Gender_QADIN VARCHAR(10),
    Marital_Status_DUL VARCHAR(10),
    Marital_Status_EVLI VARCHAR(10),
    Marital_Status_SUBAY VARCHAR(10),
    Occupation_HAYVANCILIK VARCHAR(50),
    Occupation_HIZMETLER VARCHAR(50),
    Occupation_MORTGAGES VARCHAR(50),
    Occupation_TARIM VARCHAR(50),
    Occupation_TICARET VARCHAR(50),
    Occupation_URETIM VARCHAR(50),
    Log_Monthly_Income DECIMAL(15, 6),
    Education_Level_Higher_Education VARCHAR(50),
    Education_Level_Incomplete_Secondary_Education VARCHAR(50),
    Education_Level_Other_Education VARCHAR(50),
    Education_Level_Secondary_Education VARCHAR(50),
    Education_Level_Secondary_Education_with_Specialisation VARCHAR(50),
    Total_Loan_Amount DECIMAL(15, 2),
    Average_Loan_Amount DECIMAL(15, 2),
    Loan_Amount_Range VARCHAR(50),
    Active_Loans_Count INT,
    Overdue_Loans_Count INT,
    Severely_Overdue_Loans_Count INT,
    legal_loans_count INT,
    woff_loans_count INT,
    Loan_Status_Changes VARCHAR(255),
    Average_Credit_Duration INT,
    Total_Credit_Duration INT,
    Product_Type_BIZNES_KREDITLERI VARCHAR(100),
    Product_Type_PARTNYORLUQ_KREDITLERI VARCHAR(100),
    Product_Type_ISTEHLAK VARCHAR(100),
    Product_Type_AH_LAYIHELARI VARCHAR(100),
    Total_Debt DECIMAL(15, 2),
    Debt_Income_Ratio DECIMAL(5, 2),
    Number_of_Family_Members INT,
    Is_Politician_Hayir VARCHAR(10),
    Has_Political_Affiliation_Hayir VARCHAR(10),
    Account_Purpose_SBER_HESAP VARCHAR(50),
    Account_Purpose_TASARRUF_HESABI VARCHAR(50),
    Account_Purpose_ULUSLARARASI_PARA_TRANSFERI VARCHAR(50),
    Account_Purpose_YURTICI_HAVALE VARCHAR(50),
    Has_Collateral_Hayir VARCHAR(10),
    Owns_Valuable_Items_Hayir VARCHAR(10),
    Owns_Real_Estate_Hayir VARCHAR(10),
    Loan_Purpose_ISLETME_SERMAYESI VARCHAR(50),
    Loan_Purpose_MULK_ALIMI VARCHAR(50),
    Loan_Purpose_SABIT_VARLIKLAR VARCHAR(50),
    Loan_Purpose_TADILAT VARCHAR(50),
    Loan_Purpose_TARIM VARCHAR(50),
    Income_Type_DIGER VARCHAR(50),
    Income_Type_EK_IS VARCHAR(50),
    Income_Type_HAVALE VARCHAR(50),
    Income_Type_KIRA_GELIRI VARCHAR(50),
    Negative_Comment_from_Loan_Department_Hayir VARCHAR(10),
    Job_Position_Diger VARCHAR(50),
    Job_Position_Ozel_Sektor VARCHAR(50),
    Job_Position_Ozel_Sektor_Teknik VARCHAR(50),
    Job_Position_Sirket_Sahibi VARCHAR(50),
    Job_Position_Yonetici VARCHAR(50),
    Is_Customer_on_Banned_List_Hayir VARCHAR(10),
    Is_Regular_Customer_Evet VARCHAR(10),
    Annual_Account_Activity_Range_100000_500000 VARCHAR(50),
    Annual_Account_Activity_Range_30000_100000 VARCHAR(50),
    Annual_Account_Activity_Range_500000_99999999999 VARCHAR(50),
    Annual_Account_Activity_Range_Diger VARCHAR(50),
    Target_Worst VARCHAR(255)
)