CREATE TABLE customers (
    customer_id INT,
    full_name VARCHAR(255),
    place_of_birth VARCHAR(255),
    date_of_birth DATETIME,
    citizenship VARCHAR(100),
    gender VARCHAR(10),
    number_of_children INT,
    marital_status VARCHAR(50),
    occupation VARCHAR(255),
    customer_registration_date DATETIME,
    monthly_income DECIMAL(15,2),
    education_level VARCHAR(100),
    city VARCHAR(100),
    number_of_loans INT,
    PRIMARY KEY (customer_id)
);

CREATE TABLE credit_scores (
    customer_id INT,
    credit_score INT,
    PRIMARY KEY (customer_id),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE customer_loans (
    document_id VARCHAR(50) PRIMARY KEY,
    customer_id INT,
    product_type VARCHAR(100),
    loan_type VARCHAR(100),
    currency_type VARCHAR(10),
    loan_start_date DATETIME,
    loan_end_date DATETIME,
    loan_status VARCHAR(50),
    requested_amount DECIMAL(15,2),
    approved_amount DECIMAL(15,2),
    principal_debt DECIMAL(15,2),
    total_debt DECIMAL(15,2),
    secondary_purpose_code VARCHAR(50),
    secondary_purpose_description VARCHAR(255),
    tertiary_purpose_code VARCHAR(50),
    tertiary_purpose_description VARCHAR(255),
    product_type_biznes_kredileri VARCHAR(10),
    product_type_partnyorluq_kredileri VARCHAR(10),
    product_type_istehlak VARCHAR(10),
    product_type_eh_layihələri VARCHAR(10),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE surveys (
    customer_id INT,
    country_of_residence VARCHAR(100),
    citizenship VARCHAR(100),
    is_politician VARCHAR(10),
    has_political_affiliation VARCHAR(10),
    account_purpose VARCHAR(255),
    annual_account_activity_range VARCHAR(50),
    current_account_local_currency_balance VARCHAR(50),
    number_of_current_accounts VARCHAR(50),
    savings_account_local_currency_balance VARCHAR(50),
    number_of_savings_accounts VARCHAR(50),
    investment_account_local_currency_balance VARCHAR(50),
    number_of_investment_accounts VARCHAR(50),
    authorized_signatory_country_of_residence VARCHAR(100),
    authorized_signatory_citizenship VARCHAR(100),
    company_partner_citizenship VARCHAR(100),
    number_of_family_members INT,
    gender VARCHAR(10),
    marital_status VARCHAR(50),
    education_level VARCHAR(100),
    occupation VARCHAR(255),
    age INT,
    additional_income FLOAT,
    has_collateral VARCHAR(10),
    owns_valuable_items VARCHAR(10),
    owns_real_estate VARCHAR(10),
    loan_purpose VARCHAR(255),
    loan_branch VARCHAR(100),
    number_of_loans INT,
    loan_month VARCHAR(50),
    primary_income_percentage VARCHAR(20),
    income_type VARCHAR(100),
    expense_to_income_ratio FLOAT,
    negative_comment_from_loan_department VARCHAR(10),
    years_of_employment VARCHAR(50),
    years_in_same_residence INT,
    job_position VARCHAR(255),
    movable_property_value_in_usd DECIMAL(15,2),
    immovable_property_value_land_in_usd DECIMAL(15,2),
    second_property_value_in_usd DECIMAL(15,2),
    immovable_property_value_house_in_usd DECIMAL(15,2),
    is_customer_on_banned_list VARCHAR(10),
    is_regular_customer VARCHAR(10),
    total_score INT,
    PRIMARY KEY (customer_id),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);
